//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kronos.AcceleratedTool.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kronos.AcceleratedTool.UI.Resources.ToolUI", typeof(ToolUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Testing Tool.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Users Only.
        /// </summary>
        internal static string AuthorizedUsersOnlyLabel {
            get {
                return ResourceManager.GetString("AuthorizedUsersOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format of license file..
        /// </summary>
        internal static string ErrorMsgWrongFormatOfLicenseFile {
            get {
                return ResourceManager.GetString("ErrorMsgWrongFormatOfLicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1}.
        /// </summary>
        internal static string JobStatusInfoFormat {
            get {
                return ResourceManager.GetString("JobStatusInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License has expired..
        /// </summary>
        internal static string LicenseHasExpired {
            get {
                return ResourceManager.GetString("LicenseHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is not found at &apos;{0}&apos;..
        /// </summary>
        internal static string LicenseIsNotFoundAt {
            get {
                return ResourceManager.GetString("LicenseIsNotFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to login.
        /// </summary>
        internal static string MsgConnectionTest {
            get {
                return ResourceManager.GetString("MsgConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Data not found, please Extract Employee Data via API or DB and Pay Rule Building Blocks.
        /// </summary>
        internal static string MsgEmployeeAndPayRuleJobsWereNotRun {
            get {
                return ResourceManager.GetString("MsgEmployeeAndPayRuleJobsWereNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Data Not Found, please Extract Employee Data via API or DB.
        /// </summary>
        internal static string MsgEmployeeJobWaNotRun {
            get {
                return ResourceManager.GetString("MsgEmployeeJobWaNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user credentials..
        /// </summary>
        internal static string MsgEnterCredentials {
            get {
                return ResourceManager.GetString("MsgEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid license..
        /// </summary>
        internal static string MsgEnterLicense {
            get {
                return ResourceManager.GetString("MsgEnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid start date..
        /// </summary>
        internal static string MsgEnterValidStartDate {
            get {
                return ResourceManager.GetString("MsgEnterValidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        internal static string MsgEnterValidURL {
            get {
                return ResourceManager.GetString("MsgEnterValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file is not accessible. Please close it..
        /// </summary>
        internal static string MsgFileIsNotAccessible {
            get {
                return ResourceManager.GetString("MsgFileIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Key Entered.
        /// </summary>
        internal static string MsgIncorrectPassowrdKeyEntered {
            get {
                return ResourceManager.GetString("MsgIncorrectPassowrdKeyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check source file {0}. All dates in the spreadsheet should be in range {1} and {2}..
        /// </summary>
        internal static string MsgInvalidDateRange {
            get {
                return ResourceManager.GetString("MsgInvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has failed. Please see the log file for more details..
        /// </summary>
        internal static string MsgJobFailed {
            get {
                return ResourceManager.GetString("MsgJobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job has been completed with the warnings. Please see the log file for more details..
        /// </summary>
        internal static string MsgJobWasCompletedWithSomeWarnings {
            get {
                return ResourceManager.GetString("MsgJobWasCompletedWithSomeWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is successfull..
        /// </summary>
        internal static string MsgSuccessfulLogin {
            get {
                return ResourceManager.GetString("MsgSuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URL, username or password.
        /// </summary>
        internal static string MsgUnsuccessfulLogin {
            get {
                return ResourceManager.GetString("MsgUnsuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST={Host Name})(PORT={Port}))(CONNECT_DATA=(SID={DB Instance}))).
        /// </summary>
        internal static string OracleUrlTip {
            get {
                return ResourceManager.GetString("OracleUrlTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source file is not found..
        /// </summary>
        internal static string SourceFileIsNotFoundAt {
            get {
                return ResourceManager.GetString("SourceFileIsNotFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={Server Name};Initial Catalog={DataBase Name}.
        /// </summary>
        internal static string SqlUrlTip {
            get {
                return ResourceManager.GetString("SqlUrlTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date should be greater than 1900 year..
        /// </summary>
        internal static string StartDateShouldBeGreaterThanMinimumDate {
            get {
                return ResourceManager.GetString("StartDateShouldBeGreaterThanMinimumDate", resourceCulture);
            }
        }
    }
}
