//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcceleratedTool.Jobs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobStepDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobStepDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcceleratedTool.Jobs.Resources.JobStepDescription", typeof(JobStepDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding PayCodeEdit data.
        /// </summary>
        internal static string AddPayCodeEditData {
            get {
                return ResourceManager.GetString("AddPayCodeEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Pay Code data on {0}.
        /// </summary>
        internal static string AddPayCodeEditItemsOnDate {
            get {
                return ResourceManager.GetString("AddPayCodeEditItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Punch data.
        /// </summary>
        internal static string AddPunchData {
            get {
                return ResourceManager.GetString("AddPunchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Punch In data on {0}.
        /// </summary>
        internal static string AddPunchInItemsOnDate {
            get {
                return ResourceManager.GetString("AddPunchInItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Punch Out data on {0}.
        /// </summary>
        internal static string AddPunchOutItemsOnDate {
            get {
                return ResourceManager.GetString("AddPunchOutItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Schedule data.
        /// </summary>
        internal static string AddScheduleData {
            get {
                return ResourceManager.GetString("AddScheduleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Schedule data on {0}.
        /// </summary>
        internal static string AddScheduleItemsOnDate {
            get {
                return ResourceManager.GetString("AddScheduleItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Schedule data.
        /// </summary>
        internal static string ClearScheduleItems {
            get {
                return ResourceManager.GetString("ClearScheduleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Timesheet data.
        /// </summary>
        internal static string ClearTimesheetItems {
            get {
                return ResourceManager.GetString("ClearTimesheetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Bi-Weekly &amp; PayPeriod Overtime sheet data.
        /// </summary>
        internal static string ExportBiWeeklyOvertimeSheetData {
            get {
                return ResourceManager.GetString("ExportBiWeeklyOvertimeSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Daily Overtime sheet data.
        /// </summary>
        internal static string ExportDailyOvertimeSheetData {
            get {
                return ResourceManager.GetString("ExportDailyOvertimeSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting EarlyIn sheet data.
        /// </summary>
        internal static string ExportEarlyInSheetData {
            get {
                return ResourceManager.GetString("ExportEarlyInSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting EarlyOut sheet data.
        /// </summary>
        internal static string ExportEarlyOutSheetData {
            get {
                return ResourceManager.GetString("ExportEarlyOutSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}.
        /// </summary>
        internal static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting LateIn sheet data.
        /// </summary>
        internal static string ExportLateInSheetData {
            get {
                return ResourceManager.GetString("ExportLateInSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting LateOut sheet data.
        /// </summary>
        internal static string ExportLateOutSheetData {
            get {
                return ResourceManager.GetString("ExportLateOutSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Unschedule sheet data.
        /// </summary>
        internal static string ExportUnscheduleSheetData {
            get {
                return ResourceManager.GetString("ExportUnscheduleSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Weekly Overtime sheet data.
        /// </summary>
        internal static string ExportWeeklyOvertimeSheetData {
            get {
                return ResourceManager.GetString("ExportWeeklyOvertimeSheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting PayCodeEdit data from {0}.
        /// </summary>
        internal static string ExtractPayCodeEditDataFromFile {
            get {
                return ResourceManager.GetString("ExtractPayCodeEditDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Punch data from {0}.
        /// </summary>
        internal static string ExtractPunchDataFromFile {
            get {
                return ResourceManager.GetString("ExtractPunchDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Schedule data from {0}.
        /// </summary>
        internal static string ExtractScheduleDataFromFile {
            get {
                return ResourceManager.GetString("ExtractScheduleDataFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Person Numbers of Active Employees.
        /// </summary>
        internal static string GetEmployeeNumbers {
            get {
                return ResourceManager.GetString("GetEmployeeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Exception Rules data.
        /// </summary>
        internal static string GetExceptionRuleData {
            get {
                return ResourceManager.GetString("GetExceptionRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving first {0} Employees data .
        /// </summary>
        internal static string GetFirstBunchOfFullEmployeeData {
            get {
                return ResourceManager.GetString("GetFirstBunchOfFullEmployeeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving next {0} Employees data.
        /// </summary>
        internal static string GetNextBunchOfFullEmployeeData {
            get {
                return ResourceManager.GetString("GetNextBunchOfFullEmployeeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Overtime Rules data.
        /// </summary>
        internal static string GetOvertimeRulesData {
            get {
                return ResourceManager.GetString("GetOvertimeRulesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Pay Codes data.
        /// </summary>
        internal static string GetPayCodesData {
            get {
                return ResourceManager.GetString("GetPayCodesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Pay Rule Building data.
        /// </summary>
        internal static string GetPayRuleBuildingData {
            get {
                return ResourceManager.GetString("GetPayRuleBuildingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Pay Rules data.
        /// </summary>
        internal static string GetPayRuleData {
            get {
                return ResourceManager.GetString("GetPayRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Person Punch Round data.
        /// </summary>
        internal static string GetPersonPunchRoundData {
            get {
                return ResourceManager.GetString("GetPersonPunchRoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Punch Round Rules data.
        /// </summary>
        internal static string GetPunchRoundRulesData {
            get {
                return ResourceManager.GetString("GetPunchRoundRulesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Shift Guarantee data.
        /// </summary>
        internal static string GetShiftGuaranteeData {
            get {
                return ResourceManager.GetString("GetShiftGuaranteeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Work Rules data.
        /// </summary>
        internal static string GetWorkRuleData {
            get {
                return ResourceManager.GetString("GetWorkRuleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Timesheet data from {0} to {1}.
        /// </summary>
        internal static string LoadPeriodTimesheetData {
            get {
                return ResourceManager.GetString("LoadPeriodTimesheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Timesheet data.
        /// </summary>
        internal static string LoadTimesheetData {
            get {
                return ResourceManager.GetString("LoadTimesheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing PayCodeEdit data.
        /// </summary>
        internal static string RemovePayCodeEditData {
            get {
                return ResourceManager.GetString("RemovePayCodeEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Pay Code data on {0}.
        /// </summary>
        internal static string RemovePayCodeEditItemsOnDate {
            get {
                return ResourceManager.GetString("RemovePayCodeEditItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Punch data.
        /// </summary>
        internal static string RemovePunchData {
            get {
                return ResourceManager.GetString("RemovePunchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Punch In data on {0}.
        /// </summary>
        internal static string RemovePunchInItemsOnDate {
            get {
                return ResourceManager.GetString("RemovePunchInItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Punch Out data on {0}.
        /// </summary>
        internal static string RemovePunchOutItemsOnDate {
            get {
                return ResourceManager.GetString("RemovePunchOutItemsOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Schedule data.
        /// </summary>
        internal static string RemoveScheduleData {
            get {
                return ResourceManager.GetString("RemoveScheduleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Schedule data on {0}.
        /// </summary>
        internal static string RemoveScheduleItemsOnDate {
            get {
                return ResourceManager.GetString("RemoveScheduleItemsOnDate", resourceCulture);
            }
        }
    }
}
