//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcceleratedTool.Jobs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobWarnings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobWarnings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcceleratedTool.Jobs.Resources.JobWarnings", typeof(JobWarnings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid punches.
        /// </summary>
        internal static string AllPunchesAreInvalid {
            get {
                return ResourceManager.GetString("AllPunchesAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid schedule data.
        /// </summary>
        internal static string AllSchedulesAreInvalid {
            get {
                return ResourceManager.GetString("AllSchedulesAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not data to run {0} test.
        /// </summary>
        internal static string NoDataForTestRunning {
            get {
                return ResourceManager.GetString("NoDataForTestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated punches were skipped.
        /// </summary>
        internal static string PunchDuplicates {
            get {
                return ResourceManager.GetString("PunchDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punches with empty Date value were skipped.
        /// </summary>
        internal static string PunchEmptyDate {
            get {
                return ResourceManager.GetString("PunchEmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punches with empty Day value were skipped.
        /// </summary>
        internal static string PunchEmptyDay {
            get {
                return ResourceManager.GetString("PunchEmptyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punches with empty Time value were skipped.
        /// </summary>
        internal static string PunchEmptyTime {
            get {
                return ResourceManager.GetString("PunchEmptyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule items with empty Date value were skipped.
        /// </summary>
        internal static string ScheduleEmptyDate {
            get {
                return ResourceManager.GetString("ScheduleEmptyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule items with empty Day value were skipped.
        /// </summary>
        internal static string ScheduleEmptyDay {
            get {
                return ResourceManager.GetString("ScheduleEmptyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule items with empty StartScheduleTime or EndScheduleTime value were skipped.
        /// </summary>
        internal static string ScheduleEmptyTime {
            get {
                return ResourceManager.GetString("ScheduleEmptyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors were detected in &apos;{0}&apos; file on &apos;{1}&apos; sheet:.
        /// </summary>
        internal static string ValidationErrorsMessage {
            get {
                return ResourceManager.GetString("ValidationErrorsMessage", resourceCulture);
            }
        }
    }
}
